import type { Metadata } from 'next';
import { JoinFAQ } from '../components/Interactive';
import { PageIntro, Shell } from '../components/SiteChrome';

export const metadata: Metadata = { title: '加入我们', description: '了解 InfoCo 招新方向、流程与常见问题。' };
const roles = [['</>', '我想学会编程', '从基础课程开始，在真实项目里把知识连起来。'], ['MAKE', '我想做出作品', '把游戏、网站、工具或研究想法推进到可以分享。'], ['PIXEL', '我会设计或表达', '视觉、交互、文案和叙事都是科技项目的重要部分。'], ['TEAM', '我喜欢组织与协作', '活动策划、资源协调和对外连接同样不可或缺。']];
export default function JoinPage() {
  return <Shell><main id="top"><PageIntro index="05" label="JOIN US / 加入我们" title="不需要准备好，才可以开始。" copy="无论你是第一次接触编程，还是已经有想做的项目，InfoCo 都希望给你一个清楚、友好、真正能开始行动的入口。" accent="orange" /><section className="join-status section-pad"><div><span className="status-pill">○ RECRUITMENT CLOSED</span><h2>当前招新尚未开放。</h2><p>页面不会在非招新期消失。下一次招新开放后，这里会更新公开群、报名入口、时间安排与完整流程。</p></div><a className="btn btn-dark" href="#public-channel">查看公开渠道 ↓</a></section><section className="fit-section section-pad"><div className="section-heading"><div><span className="section-index">WHO FITS HERE</span><h2>找到你的起点</h2></div><p>不设“标准社员”模板。<br />从你真正感兴趣的事情开始。</p></div><div className="role-grid">{roles.map(([icon, title, copy]) => <article key={title}><b>{icon}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="join-flow section-pad"><div className="section-heading"><div><span className="section-index light">RECRUITMENT FLOW</span><h2>加入流程</h2></div><p>正式日期与入口将在开放时补充。</p></div><div className="flow-grid">{[['01', '关注通知', '从官网或社团公开渠道获取招新时间。'], ['02', '填写意向', '通过学校系统或公开表单告诉我们你感兴趣的方向。'], ['03', '开放交流', '用一次轻松的交流互相认识，不以编程基础为唯一标准。'], ['04', '开始共创', '进入学习路径、活动团队或项目小组，完成第一次协作。']].map(([index, title, copy]) => <div key={index}><span>{index}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section><section className="join-faq section-pad"><div className="section-heading"><div><span className="section-index">FAQ / 常见问题</span><h2>没有基础，也完全没问题。</h2></div></div><JoinFAQ /></section><section className="public-channel" id="public-channel"><span>PUBLIC CHANNEL / 公开渠道</span><h2>保持连接，等待下一次信号。</h2><p>现有材料没有提供可公开使用的社交媒体、招新群或邮箱。为避免发布错误或私人联系方式，这些入口将在社团确认后更新。</p><div><strong>infoco.club</strong><span>OFFICIAL WEBSITE</span></div></section></main></Shell>;
}
